### ISSUE TITLE
is plug can used in windows gvim 8.2? got some error......

### ISSUE THREAD

**Issue by WillDawnlll** [rootkiter/hexedit#4]
E485 , cant read temp file in windows, maybe reason is  escape character  "\\"in path? 
similar problem in plug-vim , when i change default shell from cmd to powershell ....
ps: i use plug-vim install

**Comment by rootkiter** [comment]
Didn't test VIM in Windows before. Can you help fix it, or provide more detailed information?

**Comment by WillDawnlll** [comment]
111, and my bad , last comment dont display "\\" ...... i think may be that related to the reason, (when i change default shell from cmd to powershell,  same error e484 show up in  vim-plug(cant open temp file), for e484 i searched some tips about escape character ), (cant read temp file is so weird exclude permissions issue )

**Comment by WillDawnlll** [comment]
test in kali vim 7.1 , plug work ok, and here is a screenshot in win gvim
![图片](https://user-images.githubusercontent.com/28567110/99765126-61ddfb00-2b39-11eb-8164-3d1277df3b29.png)
